# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: buildimage
  jobs:
  - job: Build
    displayName: buildjob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: pipeline build stage
      inputs:
        repository: 'wingsorg/wingsannoapi'
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          v2.1
    - task: Docker@2
      displayName: pipeline push stage
      inputs:
        containerRegistry: |
          wingsrouterservice
        repository: 'wingsorg/wingsannoapi'
        command: push
        tags: |
          v2.1
